version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: petlovers_db
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  api:
    stdin_open: true
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: petlovers_api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /home/backend/app/node_modules
      - ./backend:/home/backend/app

volumes:
  postgres-data:
  pgadmin-data:
        
    