import Head from "next/head"
import React from "react"
import Header from "../Header"

const Layout: React.FC<{ children: JSX.Element }> = ({ children }) => {
    return (
        <>
            <Head>
                <title>Pet Lovers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {children}
            footer
        </>
    )
}

export default Layout