import Head from 'next/head'
import Link from 'next/link'
import petshops from "../JSON/petshops.json"
import EastIcon from '@mui/icons-material/East';

const ThreePetshops = () => {
  return (
    <section className='border-2 text-center'>
      <h1 className='font-noto-sans text-4xl text-emerald-400'
      >Petshops Cadastradas</h1>
      <div></div>
      <Link className='font-noto-sans font-bold text-xl text-stone-600' href="/petshops">LISTAR TODOS<EastIcon /></Link>
    </section>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Pet Lovers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <ThreePetshops />
      </main>
    </>
  )
}